/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia;

import listas.Multilistas;
import listas.Nodo;
import proyu3u4.Institucion;

/**
 *
 * @author Daniel Castrejon
 */
public class VentanaInstitucion extends javax.swing.JFrame
{

    /**
     * Creates new form VentanaInstitucion
     */
    public VentanaInstitucion()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        agregarButton = new javax.swing.JButton();
        dirLabel = new javax.swing.JLabel();
        dirTextField = new javax.swing.JTextField();
        cveInstitucionLabel = new javax.swing.JLabel();
        cveTextField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nomTextField = new javax.swing.JTextField();
        telLabel = new javax.swing.JLabel();
        telTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TECNOLOGICOS");

        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarButtonActionPerformed(evt);
            }
        });
        agregarButton.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                agregarButtonKeyPressed(evt);
            }
        });

        dirLabel.setText("Director");

        dirTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dirTextFieldActionPerformed(evt);
            }
        });

        cveInstitucionLabel.setText("Clave Institucion");

        nombreLabel.setText("Nombre");

        telLabel.setText("Telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dirLabel)
                                .addGap(50, 50, 50)
                                .addComponent(dirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cveInstitucionLabel)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(telLabel)
                                            .addComponent(nombreLabel))
                                        .addGap(49, 49, 49)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cveTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(nomTextField)
                                    .addComponent(telTextField))))
                        .addGap(0, 107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarButton)
                        .addGap(18, 18, 18)
                        .addComponent(dirLabel)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cveInstitucionLabel)
                    .addComponent(cveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telLabel)
                    .addComponent(telTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarButtonActionPerformed
    {//GEN-HEADEREND:event_agregarButtonActionPerformed
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void dirTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dirTextFieldActionPerformed
    {//GEN-HEADEREND:event_dirTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirTextFieldActionPerformed

    private void agregarButtonKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_agregarButtonKeyPressed
    {//GEN-HEADEREND:event_agregarButtonKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            Institucion ins = new Institucion("", 0, "", 0);
            Object objInst = ins.datos(dirTextField.getText(), Integer.parseInt(cveTextField.getText()), nomTextField.getText(), Integer.parseInt(telTextField.getText()));
            Nodo p = new Nodo(objInst, nomTextField.getText());
            String etiqueta[] = new String[1];
            etiqueta[0] = nomTextField.getText();
            VentanaP.raiz = Multilistas.insertar(VentanaP.raiz, p, 0, etiqueta);
            dirTextField.setText("");
            dirTextField.requestFocus();
            cveTextField.setText("");
            cveTextField.requestFocus();
            nomTextField.setText("");
            nomTextField.requestFocus();
            telTextField.setText("");
            telTextField.requestFocus();
            System.out.println(Multilistas.desp(VentanaP.raiz, 0));
            this.setVisible(false);
        }
    }//GEN-LAST:event_agregarButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VentanaInstitucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JLabel cveInstitucionLabel;
    private javax.swing.JTextField cveTextField;
    private javax.swing.JLabel dirLabel;
    private javax.swing.JTextField dirTextField;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel telLabel;
    private javax.swing.JTextField telTextField;
    // End of variables declaration//GEN-END:variables
}
